### ISSUE TITLE
Deatils of Project

### ISSUE THREAD

**Issue by memeghaj10** [deckardmehdy/myPath#1]
Hi, please could you share a brief view about how you went on and build this cool project.
Would love to hear that....

**Comment by deckardmehdy** [comment]
Hi Memeghaj10,

I saw clement mihailescu‘s pathfinding visualizer Project, and I decided that I could improve upon his code and make it more efficient. I started off with simple algorithms, such as DFS and BFS, and added more. :)

**Comment by memeghaj10** [comment]
Well that's great.
Would you mind if I could talk to you in a chat or email more about this project.
